name: interview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Assets generator
  flutter_gen: ^5.9.0

  get_it: ^8.0.3

  # Cupertino Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    enabled: true
